# Generated by Django 2.0 on 2019-11-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
